<?php

namespace MP\CompBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
        public function findByUser($id)
        {
          $qb = $this->createQueryBuilder('a')
              ->leftJoin('a.dealer', 'c')
              ->addSelect('c');

          $qb->where('c.id LIKE :id')->setParameter('id', $id)
          ;

          return $qb
            ->getQuery()
            ->getResult()
          ;
        }
            
    public function findBylerner($id)
        {
          $qb = $this->createQueryBuilder('a')
              ->leftJoin('a.lerners', 'c')
              ->addSelect('c');

          $qb->where('c.id LIKE :id')->setParameter('id', $id)
          ;

          return $qb
            ->getQuery()
            ->getResult()
          ;
        }
        
    public function findByRecherche($recherche)
    {
  
      $qb = $this->createQueryBuilder('a');

      $qb 
            ->innerJoin('a.dealer', 'd')
            ->innerJoin('a.competence', 'c')
            ->addSelect('d')
            ->addSelect('c')
            ->where('c.name LIKE :id')
            ->orwhere('a.date LIKE :id')
            //->orwhere('adr.code LIKE :id')
            ->orwhere('d.username LIKE :id')
            
            ->setParameter('id', '%'.$recherche.'%')
            //->orderBy('a.datedebut', 'ASC')
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
