<?php

namespace MP\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
        
    public function findByUser($id)
    {
      $qb = $this->createQueryBuilder('a');

      $qb->where('a.user = :id')->setParameter('id', $id)
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
