  
mp_comp_add:
    path:     /add
    defaults: { _controller: MPCompBundle:Default:add }
  
mp_comp_home:
    path:    /{page}
    defaults:  { _controller: MPCompBundle:Default:index, page: 1 }
    requirements: 
        page: '\d+'
    
mp_comp_view:
    path:    /comp/{id}
    defaults:  { _controller: MPCompBundle:Default:view }
    requirements: 
        id: '\d+'

mp_comp_edit:
    path:    /edit/{id}
    defaults:  { _controller: MPCompBundle:Default:edit }
    requirements: 
        id: '\d+'
        
mp_comp_recherche:
    path:    /recherche
    defaults:  { _controller: MPCompBundle:Default:recherche }
